name: meetups-api-microservices
run-name: ${{ github.actor }} test meetups service
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Move meetup directory
      - run: cd microservices/meetups
      - name: Install dependecies
      - run: npm install
      - name: Build Project
      - run: npm run build
      